---
# Here we are using the debian package if debian
- include_vars: "{{ ansible_os_family }}.yml"

- debug: msg="Install Mode is {{mesos_mode}}"

- name: Check if upstart exists
  stat: path=/etc/init/
  register: etc_init

# Here we are using the debian package if debian
- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags: ['mesos', 'bootstrap']

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: ['mesos', 'bootstrap']

- name: create work dir
  file: path={{ mesos_work_dir }} state=directory

- include: upstart-init.yml
  when: etc_init.stat.exists == true and ansible_service_mgr != 'systemd'
  tags: ['mesos', 'bootstrap']

- include: systemd-init.yml
  when: ansible_service_mgr == 'systemd'
  tags: ['mesos', 'bootstrap']

- meta: flush_handlers
  tags: ['mesos']
