---

- name: Disable mesos leader
  become: yes
  command: systemctl disable zookeeper
  when: mesos_mode == "follower"
  tags: ['mesos', 'bootstrap']

- name: Disable mesos follower
  become: yes
  command: systemctl disable zookeeper
  when: mesos_mode == "leader"
  tags: ['mesos', 'bootstrap']

- name: Remove upstart configuration - replaced by systemd config
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/default/mesos-master
    - /etc/default/mesos-slave
    - /etc/init/mesos-master.conf
    - /etc/init/mesos-slave.conf
    - /etc/mesos-slave
    - /etc/mesos
  tags: ['mesos', 'bootstrap' ]

- include: systemd-leader-init.yml
  when: mesos_mode == "leader" or mesos_mode == "mixed"
  tags: ['mesos', 'bootstrap' ]

- include: systemd-follower-init.yml
  when: mesos_mode == "follower" or mesos_mode == "mixed"
  tags: ['mesos', 'bootstrap' ]
