---

- name: Write mesos-slave.service file
  become: yes
  template:
    src: mesos-slave.service.j2
    dest: /lib/systemd/system/mesos-slave.service
  tags: ['mesos', 'bootstrap']

- name: Create sysconfig folder
  become: yes
  file:
    path: /etc/sysconfig
    state: directory
  tags: ['bootstrap']

- name: Configure mesos-slave
  become: yes
  template:
    src: mesos-agent.sysconfig.j2
    dest: /etc/sysconfig/mesos-agent
  tags: ['mesos', 'bootstrap']

- name: Write mesos-slave credential
  when: do_mesos_follower_auth|bool
  become: yes
  copy:
    dest: /etc/sysconfig/mesos-agent-credential
    content: "{{ mesos_follower_principal }} {{ mesos_follower_secret }}"
    mode: 0600
  tags: ['mesos', 'bootstrap']

- name: Delete credential
  when: not do_mesos_follower_auth|bool
  become: yes
  file:
    dest: /etc/sysconfig/mesos-agent-credential
    state: absent
  tags: ['mesos', 'bootstrap']

- name: Enable mesos-slave service
  become: yes
  command: systemctl enable mesos-slave
  tags: ['mesos', 'bootstrap']

- name: Start mesos-slave
  systemd:
    name: mesos-slave
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: ['mesos']
