---

- name: Write mesos-master.service file
  become: yes
  template:
    src: mesos-master.service.j2
    dest: /lib/systemd/system/mesos-master.service
  tags: ['mesos', 'bootstrap']

- name: Create sysconfig folder
  become: yes
  file:
    path: /etc/sysconfig
    state: directory
  tags: ['bootstrap']

- name: Configure mesos-master
  become: yes
  template:
    src: mesos-master.sysconfig.j2
    dest: /etc/sysconfig/mesos-master
  tags: ['mesos', 'bootstrap']

- name: Write leader credentials
  become: yes
  when: do_mesos_framework_auth|bool or do_mesos_follower_auth|bool
  template:
    src: master-credentials.j2
    dest: /etc/sysconfig/mesos-credentials
    mode: 0600
  tags: ['mesos', 'bootstrap']

- name: Delete leader credentials
  become: yes
  when: not do_mesos_framework_auth|bool and not do_mesos_follower_auth|bool
  file:
    dest: /etc/sysconfig/mesos-credentials
    state: absent
  tags: ['mesos', 'bootstrap']

- name: Enable mesos-master service
  become: yes
  command: systemctl enable mesos-master
  tags: ['mesos', 'bootstrap']

- name: Start mesos-master
  systemd:
    name: mesos-master
    state: restarted
    daemon_reload: yes
    enabled: yes
  tags: ['mesos']

